source "https://rubygems.org"
# Replace 4.0.3 with the version of Foundation you want to use

gem "compass"
gem 'sass-globbing'           # Import Sass files based on globbing pattern.

# For more information on this file see:
# http://foundation.zurb.com/docs/sass.html
# http://zslabs.com/articles/versioned-dependencies-with-compass
