<?php
/**
 * @file
 * Custom code additions for the DDC.
 */

/**
 * Implements hook_theme().
 */
function ddc_custom_theme($existing, $type, $theme, $path) {
  return array(
    'ddc_custom_article_author' => array(
      'variables' => array('node' => NULL),
    )
  );
}

/**
 * Default pre-processing for the custom article author theme function.
 */
function template_preprocess_ddc_custom_article_author(&$variables) {
  $user = user_load($variables['node']->uid);
  $user_view = user_view($user);
  $variables['user'] = $user;
  $variables['author'] = drupal_render($user_view);
}

/**
 * Default theme implementation for ddc_custom_article_author.
 */
function theme_ddc_custom_article_author($variables) {
  $output = '<h4>' . t('About the author') . '</h4>';
  $output .= '<div class="author-wrapper">';
  $output .= $variables['user']->name;
  $output .= $variables['author'];
  $output .= '</div>';
  return $output;
}

/**
 * Checks whether the given node is flagged as highlighted.
 */
function ddc_custom_article_is_highlighted($node) {
  $items = field_get_items('node', $node, 'field_highlighted');
  return !empty($items);
}
